// Firmware generated by ProjectForge AI
// Target: Arduino Mega
// Task: Line Follower Robot logic: Read IR sensors. If left sensor detects line, turn left. If right sensor detects line, turn right. If both detect line, move forward. Use L298N Motor Driver connected to Arduino Uno and DC Motors. Powered by 9V Battery.

#include <Arduino.h>

const int LED_PIN = 13; // default pin

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  Serial.println("Arduino Mega initialised for: Line Follower Robot logic: Read IR sensors. If left sensor detects line, turn left. If right sensor detects line, turn right. If both detect line, move forward. Use L298N Motor Driver connected to Arduino Uno and DC Motors. Powered by 9V Battery.");
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(1000);
  digitalWrite(LED_PIN, LOW);
  delay(1000);
  Serial.println("System heartbeat nominal...");
}