// Firmware generated by ProjectForge AI
// Target: ESP32
// Task: ESP32 Development Board – 1
MQ-135 Gas Sensor – 1
Flame Sensor Module – 1
DHT11/DHT22 Temperature & Humidity Sensor – 1
OLED Display (0.96" I2C) – 1
Buzzer – 1
Red LED – 1
Green LED – 1
220Ω Resistors – 2
Breadboard – 1
Jumper Wires – 20–30
5V Power Supply / Power Bank – 1

#include <Arduino.h>

const int LED_PIN = 13; // default pin

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  Serial.println("ESP32 initialised for: ESP32 Development Board – 1
MQ-135 Gas Sensor – 1
Flame Sensor Module – 1
DHT11/DHT22 Temperature & Humidity Sensor – 1
OLED Display (0.96\" I2C) – 1
Buzzer – 1
Red LED – 1
Green LED – 1
220Ω Resistors – 2
Breadboard – 1
Jumper Wires – 20–30
5V Power Supply / Power Bank – 1");
}

void loop() {
  digitalWrite(LED_PIN, HIGH);
  delay(1000);
  digitalWrite(LED_PIN, LOW);
  delay(1000);
  Serial.println("System heartbeat nominal...");
}